project:
  type: website
  resources: 
    - resume.pdf

website:
  title: "Sophia Angelene Santos"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Portfolio
      - href: contact.qmd
        text: Contact
  page-footer: 
    right: "&copy; 2026, Sophia Angelene Santos"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    published-title: "Last updated"
    reference-location: document
    code-fold: false
    fontsize: 1.3em

execute: 
  freeze: auto

