---
title: "Coursework"
toc: true
---

I list my relevant coursework below. I have bolded the courses that I find most relevant to industry today.

### UCLA Courses
- **Practice of Statistical Consulting (STATS 140XP,141XP)**  
- Applied Sampling (STATS C155)  
- Introduction to Computational Statistics with R (STATS 102A)  
- Introduction to Computation and Optimization for Statistics (102B)  
- Introduction to Monte Carlo Methods (102C)  
- **Introduction to Data Analysis and Regression (STATS 101A)**  
- Introduction to Design and Analysis of Experiment (101B)  
- Introduction to Statistical Models and Data Mining (101C)  
- Introduction to Probability (STATS 100A)  
- Introduction to Mathematical Statistics (100B)  
- Linear Models (100C)  
- Introduction to Statistical Programming with R (STATS 20)  
- Introduction to Statistical Reasoning (STATS 10)  
- Introduction to Critical Cartography and Mapping Theory (DH 150)  
- **Social Media Data Analytics (DH 120)**  
- **Introduction to Digital Humanities (DH 101)**  
- **Entrepreneurship and Venture Initiation (MGMT 160)**  
- Linear Algebra (MATH 115A)  
- Introduction to Discrete Structures (MATH 61)  
- Differential Equations (MATH 33B)  
- Linear Algebra and Applications (MATH 33A)  
- Calculus of Several Variables (MATH 32A,B)  
- **Internet and Society (INF STD 30)**  
- **Information and Power (INF STD 10)**  

### College of the Canyons Courses
- **C++ Obj. Oriented Programming (CMPSCI 236)**  
- **C Programming (CMPSCI 235)**

### Canyon High School Courses
- **Honors App Development**  
- **AP Computer Science A**  
- AP Computer Science Principles  
- **AP Statistics**  
- AP Calculus AB,BC


